//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompany
    {
        public int compID { get; set; }
        public string compName { get; set; }
        public string compRep { get; set; }
        public System.DateTime compDOE { get; set; }
        public string compAddr { get; set; }
        public string compCat { get; set; }
        public string compEmail { get; set; }
        public string compContact { get; set; }
        public string compDesc { get; set; }
    }
}
